version: '3.8'

networks:
  ansible-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    driver: bridge

services:
  ansible-control:
    build:
      context: ./controller
      dockerfile: Dockerfile
    volumes:
      - ./controller/ansible:/usr/src/app/ansible
    networks:
      ansible-network:
        ipv4_address: 172.20.0.2

  worker-node1:
    build:
      context: ./worker
    networks:
      ansible-network:
        ipv4_address: 172.20.0.3

  worker-node2:
    build:
      context: ./worker
    networks:
      ansible-network:
        ipv4_address: 172.20.0.4
